### ISSUE TITLE
Settings objects limits not loading and not all OneAgents detected

### ISSUE THREAD

**Issue by mariusrusuTNG** [dynatrace-oss/CustomerSuccess#6]
We have discovered two issues:
1. The section "🚫 Dynatrace Limits" is not loading despite clicking `retry`
![image](https://github.com/user-attachments/assets/68868187-f6d5-4b78-87d4-4bf190976119)

3. We see a total of 13k Hosts but when comparing this to the "✳️ Dynatrace Fleet Management" section, we only see approx. 10k Hosts

This occurs on our productive tenant with approx. 2k MZs and a lot of OneAgents.

**Comment by tcontassot** [comment]
Hi!

Thanks for your feedback. I've been reviewing and implementing several performance improvements in the past few weeks.

Please note that there's still a hard timeout of 120s for each execution of AppEngine functions. Tenants with more than 10k hosts will certainly reach that timeout anyway on certain compute/request-heavy code tiles and that's expected. To put things in perspective, thousands of SDK calls are performed at each full reload of the DTR dashboard, some of its code tiles are sending hundreds of calls (eg. Limits analysis), somewhat proportional to the amount of entities and configurations in a tenant under review.

What's new with the latest 1.10.3 release are mainly those two performance improvements:

- the OneAgent version analysis now crawls the entire list of OneAgents to provide more accurante numbers, until possibly reaching a timeout after 100s.
- the Limits analysis now stops a few seconds before the AppEngine function's timeout (120s).

When one of those tiles is preemptively stopped (before the hard timeout), its results are partial and represent all the data collected and crunched before it got stopped.

I hope that helps you get more value from the DTR, at high scale.
